server:
  port: 8010
  servlet:
    context-path: /pc-builder

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    url: jdbc:mysql://localhost:3306/pcbuilder_db?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: toor
  jpa:
    database: mysql
    properties.hibernate:
      show_sql: true
      format_sql: true
  liquibase:
    url: ${spring.datasource.url}
    default-schema: pcbuilder_db
    change-log: classpath:/liquibase/liquibase-changelog.yml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
